#!/usr/bin/env bash
#
# Guards the release-build properties that are easy to lose silently.
#
# 1. Single ABI. `gen/android` is generated, so the arm64-only patch in
#    buildSrc/.../RustPlugin.kt is undone by any `tauri android init`. The
#    durable defence is `--target aarch64` in the build command (see the
#    `android:build` npm script); this check is what notices when neither
#    mechanism is in place. Four ABIs is a ~52 MB APK.
#
# 2. Size ceiling. Catches the loss of `[profile.release]` in
#    src-tauri/Cargo.toml or `isShrinkResources` in the release build type,
#    both of which fail open, the build still succeeds, just much fatter.
#
# 3. Application id. Local builds must be app.pabloagent.local so they install
#    beside the released app; only the GitHub release workflow, which sets
#    ORG_GRADLE_PROJECT_githubApk=true, ships the bare app.pabloagent.
#
# Usage: scripts/verify-apk.sh <path-to-apk>   (override with MAX_BYTES=…)

set -euo pipefail

APK=${1:?usage: scripts/verify-apk.sh <path-to-apk>}
# Currently ~8.7 MB. Leaves room to grow while still catching the 15 MB
# (no release profile) and 52 MB (all four ABIs) regressions.
MAX_BYTES=${MAX_BYTES:-11000000}

[ -f "$APK" ] || { echo "FAIL: no such APK: $APK"; exit 1; }

abis=$(unzip -l "$APK" | grep -oE 'lib/[^/]+/' | sort -u | tr -d ' ')

if [ "$abis" != "lib/arm64-v8a/" ]; then
  echo "FAIL: expected arm64-v8a only, found:"
  echo "$abis" | sed 's/^/  /'
  echo
  echo "Likely cause: RustPlugin.kt was regenerated by \`tauri android init\`,"
  echo "and the build did not pass --target aarch64. Use \`npm run android:build\`."
  exit 1
fi

size=$(stat -c %s "$APK")

if [ "$size" -gt "$MAX_BYTES" ]; then
  echo "FAIL: APK is $size bytes, ceiling is $MAX_BYTES."
  echo
  echo "Likely cause: [profile.release] (strip/lto) missing from"
  echo "src-tauri/Cargo.toml, or isShrinkResources dropped from the release"
  echo "build type in gen/android/app/build.gradle.kts."
  exit 1
fi

aapt2=$(find "${ANDROID_HOME:-/opt/android-sdk}/build-tools" -name aapt2 2>/dev/null | sort -V | tail -1)

if [ -z "$aapt2" ]; then
  echo "FAIL: no aapt2 under ANDROID_HOME to check the application id."
  exit 1
fi

package=$("$aapt2" dump badging "$APK" | sed -n "s/^package: name='\([^']*\)'.*/\1/p")
expected=app.pabloagent.local
[ "${ORG_GRADLE_PROJECT_githubApk:-}" = "true" ] && expected=app.pabloagent

if [ "$package" != "$expected" ]; then
  echo "FAIL: application id is $package, expected $expected."
  echo
  echo "Local builds get the .local suffix by default; only the GitHub release"
  echo "workflow sets ORG_GRADLE_PROJECT_githubApk=true for the bare id. Check"
  echo "the release build type in gen/android/app/build.gradle.kts."
  exit 1
fi

echo "OK: single ABI ($abis), $size bytes (ceiling $MAX_BYTES), id $package."
